### ISSUE TITLE
[3.3.5]server crash

### ISSUE THREAD

**Issue by mynew4** [TrinityCore/TrinityCore#15668]
Branch: 3.3.5
This happened some time after commit:https://github.com/TrinityCore/TrinityCore/commit/dcb7082277447c21b11c4a1d59f105fa342c172e

SpellAuras.cpp   line=1025

===================================================================
crash log

```
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/media/ubuntu/0004F6920007D69F/server/bin/worldserver'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  Trinity::Assert (
    file=file@entry=0x1c55640 "/src/server/game/Spells/Auras/SpellAuras.cpp", line=line@entry=1025, 
    function=function@entry=0x1c55ca0 <Aura::UnregisterSingleTarget()::__FUNCTION__> "UnregisterSingleTarget", message=message@entry=0x1c25563 "caster")
    at /src/common/Debugging/Errors.cpp:43
---Type <return> to continue, or q <return> to quit---
43	    *((volatile int*)NULL) = 0;
(gdb) bt
#0  Trinity::Assert (
    file=file@entry=0x1c55640 "/src/server/game/Spells/Auras/SpellAuras.cpp", line=line@entry=1025, 
    function=function@entry=0x1c55ca0 <Aura::UnregisterSingleTarget()::__FUNCTION__> "UnregisterSingleTarget", message=message@entry=0x1c25563 "caster")
    at /src/common/Debugging/Errors.cpp:43
#1  0x00000000010d4d36 in Aura::UnregisterSingleTarget (
    this=this@entry=0x7f379586bac0)
    at /src/server/game/Spells/Auras/SpellAuras.cpp:1025
#2  0x0000000000dc0d8d in Unit::RemoveOwnedAura (this=0x7f37b875a000, i=..., 
    removeMode=AURA_REMOVE_BY_DEATH)
    at /src/server/game/Entities/Unit/Unit.cpp:3609
#3  0x0000000000df0074 in Unit::RemoveAllAurasOnDeath (
    this=this@entry=0x7f37b875a000)
    at /src/server/game/Entities/Unit/Unit.cpp:4120
#4  0x0000000000dfa44b in Unit::setDeathState (this=0x7f37b875a000, 
    s=JUST_DIED)
    at /src/server/game/Entities/Unit/Unit.cpp:12570
---Type <return> to continue, or q <return> to quit---
#5  0x0000000000d93de2 in Player::setDeathState (this=0x7f37b875a000, 
    s=<optimized out>)
    at /src/server/game/Entities/Player/Player.cpp:1966
#6  0x0000000000e01ebb in Unit::Kill (this=this@entry=0x7f379e0c4000, 
    victim=victim@entry=0x7f37b875a000, 
    durabilityLoss=durabilityLoss@entry=true)
    at /src/server/game/Entities/Unit/Unit.cpp:15465
#7  0x0000000000e03ad6 in Unit::DealDamage (this=this@entry=0x7f379e0c4000, 
    victim=victim@entry=0x7f37b875a000, damage=5556, 
    cleanDamage=cleanDamage@entry=0x7f37f77fe610, 
    damagetype=damagetype@entry=DIRECT_DAMAGE, 
    damageSchoolMask=SPELL_SCHOOL_MASK_NORMAL, spellProto=0x0, 
    durabilityLoss=true)
    at /src/server/game/Entities/Unit/Unit.cpp:748
#8  0x0000000000e0b868 in Unit::DealMeleeDamage (
    this=this@entry=0x7f379e0c4000, 
    damageInfo=damageInfo@entry=0x7f37f77fe750, 
    durabilityLoss=durabilityLoss@entry=true)
    at /src/server/game/Entities/Unit/Unit.cpp:1381
---Type <return> to continue, or q <return> to quit---
#9  0x0000000000e0dd1f in Unit::AttackerStateUpdate (this=0x7f379e0c4000, 
    victim=victim@entry=0x7f37b875a000, attType=attType@entry=BASE_ATTACK, 
    extra=extra@entry=false)
    at /src/server/game/Entities/Unit/Unit.cpp:1989
#10 0x00000000011e806c in UnitAI::DoMeleeAttackIfReady (this=0x7f3791035f40)
    at /src/server/game/AI/CoreAI/UnitAI.cpp:54
#11 0x0000000000ca3f67 in Creature::Update (this=this@entry=0x7f379e0c4000, 
    diff=diff@entry=101)
    at /src/server/game/Entities/Creature/Creature.cpp:546
#12 0x0000000001315cce in TempSummon::Update (this=0x7f379e0c4000, diff=101)
    at /src/server/game/Entities/Creature/TemporarySummon.cpp:48
#13 0x0000000000ef0b41 in Trinity::ObjectUpdater::Visit<Creature> (
    this=this@entry=0x7f37f77fedc0, m=...)
    at /src/server/game/Grids/Notifiers/GridNotifiers.cpp:347
#14 0x0000000000ff89c7 in VisitorHelper<Trinity::ObjectUpdater, Creature> (
    c=..., v=...)
    at /src/server/shared/Dynamic/TypeContainerVisitor.h:45
---Type <return> to continue, or q <return> to quit---
#15 VisitorHelper<Trinity::ObjectUpdater, Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > (c=..., v=...)
    at /src/server/shared/Dynamic/TypeContainerVisitor.h:51
#16 VisitorHelper<Trinity::ObjectUpdater, GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > (c=..., v=...)
    at /src/server/shared/Dynamic/TypeContainerVisitor.h:52
#17 VisitorHelper<Trinity::ObjectUpdater, TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > (c=..., v=...)
    at /src/server/shared/Dynamic/TypeContainerVisitor.h:58
#18 Visit (c=..., this=0x7f37f77fedd0)
    at /src/server/shared/Dynamic/TypeContainerVisitor.h:92
#19 Visit<Trinity::ObjectUpdater> (visitor=..., this=0x7f3786e3e2e8)
    at /src/server/game/Grids/Grid.h:91
#20 VisitGrid<Trinity::ObjectUpdater, TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > (visitor=..., 
    y=<optimized out>, x=1, this=<optimized out>)
    at /src/server/game/Grids/NGrid.h:157
---Type <return> to continue, or q <return> to quit---
#21 Visit<Trinity::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > > (
    visitor=..., cell=..., this=0x7f378cc06000)
    at /src/server/game/Maps/Map.h:810
#22 Map::VisitNearbyCellsOf (this=0x7f378cc06000, obj=<optimized out>, 
    gridVisitor=..., worldVisitor=...)
    at /src/server/game/Maps/Map.cpp:647
#23 0x0000000000fff769 in Map::Update (this=this@entry=0x7f378cc06000, 
    t_diff=t_diff@entry=101)
    at /src/server/game/Maps/Map.cpp:689
#24 0x0000000000fffac0 in InstanceMap::Update (this=0x7f378cc06000, t_diff=101)
    at /src/server/game/Maps/Map.cpp:3098
#25 0x0000000001012931 in call (this=0x7f37c479a580)
    at /src/server/game/Maps/MapUpdater.cpp:42
#26 MapUpdater::WorkerThread (
    this=0x23a4be8 <MapManager::instance()::instance+168>)
    at /src/server/game/Maps/MapUpdater.cpp:113
---Type <return> to continue, or q <return> to quit---
#27 0x00007f382543ae30 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#28 0x00007f382615a6aa in start_thread (arg=0x7f37f77ff700)
    at pthread_create.c:333
#29 0x00007f3824b9eeed in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb)

**Comment by pete318** [comment]
Do you know how to reproduce this? I spotted the comment on the commit the other day and I can see that it's potentially possible to have no caster. However, I couldn't find a way to reproduce it.

**Comment by mynew4** [comment]
@pete318  I do not know how it happened。

**Comment by Nyeriah** [comment]
Is that a full crash log? I got these with some local variables

http://pastebin.com/peF1Vgm7 - http://www.wowhead.com/spell=69060/frost-nova from Forge of Souls in the locals
http://pastebin.com/3Qqx106L - http://www.wowhead.com/spell=55039/gnomish-lightning-generator in the locals
http://pastebin.com/VeMA9sEx - http://www.wowhead.com/spell=50811/shatter Krystallus shatter

They don't really mean a lot to me, hopefully they can help you in any way

**Comment by Pirricli** [comment]
http://pastebin.com/MkPcpkRY

cdb16c5181b0ad02e5dd3a4afa44151fb119b62e

**Comment by pete318** [comment]
Please try with c9258d436bf2a041ad71c3d7ed068848310365c8

**Comment by MrSmite** [comment]
Just wondering, would it be more efficient to store the single target auras in their own list?

> m_ownedAurasSingleTarget

This way you don't have to iterate over auras that you know aren't single target.

**Comment by pete318** [comment]
But, surely then you'd simply be swapping more efficiency during aura removal for less every time you add and remove one of those auras.

**Comment by Shauren** [comment]
There really is no difference whether you iterate a map that has 5 elements vs 100 elements, this is way too small scale for it to have any meaningful impact (and this method is not called very often)

**Comment by MrSmite** [comment]
> this is way too small scale for it to have any meaningful impact

Ah, ok. I wasn't sure how this was for large population servers and how many auras a Unit normally had.

**Comment by Aokromes** [comment]
Fixed few days ago.
