### ISSUE TITLE
[3.3.5] Crash MapManager::GenerateInstanceId()

### ISSUE THREAD

**Issue by kabestrus** [TrinityCore/TrinityCore#19931]
**Description:**

The server crash when a player enter in an instance

**Current behaviour:**
After the change of this commit 2639056071597edfdf74b31a16ce644610a1b6d9
The server crash when a player enters in an instance
https://gist.github.com/kabestrus/39d23945af1349efdbe66eb2fa173326.

**Expected behaviour:**

Player should enter in the instance and the server shouldn't crash

**Steps to reproduce the problem:**

1. Get a fresh code and compile it
2. Enter in an instance

**Branch(es):**

3.3.5, (but i don't know if in master crash too)

**TC rev. hash/commit:** 

Revision: TrinityCore rev. 7874bee7bfb7 2017-06-19 04:04:21 -0300 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**TDB version:** 
TDB 335.63

**Operating system:** 
Windows Server 2012 R2 x64

**Compiler**
Visual Studio 2017

**Boost**
1.64

**Comment by Aokromes** [comment]
Cannot reproduce.

[11:09:42] TrinityCore rev. 9f765a162092 2017-06-20 13:31:36 -0300 (3.3.5 branch) (Unix, None, Static)
[11:10:16] You are indoors.
[11:10:16] Map: 576 (The Nexus) Zone: 4265 (The Nexus) Area: 4265 (The Nexus) Phase: 4294967295

**Comment by kabestrus** [comment]
Lol,  i'm going to update the core to the latest version and I'll try an other time

**Comment by jackpoz** [comment]
@Aokromes can you try mapID 631 ? that's the one from the crashlog

**Comment by kabestrus** [comment]
The problem is not unique from map  631.
https://gist.github.com/kabestrus/341957d1d28bf9c8f2df42b240e8a8c0

**Comment by codeman8214** [comment]
This is strange I cannot get it to crash on me I even tried loading it over & over.

**Comment by kabestrus** [comment]
The number of threads in
MapUpdate.Threads = 1
may be a problem?

**Comment by Aokromes** [comment]
Tested: Mana-tombs, Sethekk halls, icc

[12:30:55] TrinityCore rev. 2d2c71cc754f 2017-06-20 20:12:53 +0200 (3.3.5 branch) (Unix, None, Static)
[12:31:29] Welcome to Icecrown Citadel (10 Player). Instance locks are scheduled to expire in 5 Days 19 Hours.

**Comment by Shauren** [comment]
For anyone who can reproduce this, I would like to know the contents of character_instance, group_instance and instance tables in character db

**Comment by codeman8214** [comment]
@kabestrus Are you using any addons when this crashes

**Comment by Aokromes** [comment]
btw, the only effect i get after that shauren's commit is:

SQL(p): INSERT INTO instance (id, map, resettime, difficulty, completedEncounters, data) VALUES (2, 604, 0, 1, 23, 'G D 3 3 3 3 5 2 2 2 ')
[ERROR]: [1062] Duplicate entry '2' for key 'PRIMARY'

**Comment by kabestrus** [comment]
Hi @Shauren , Both tables are empty
@codeman8214 No, I'm not using any addon

Ty for the support

**Comment by codeman8214** [comment]
@kabestrus Do you remember which instance you entered when this crashed, what level were you and did you use any spells before you entered this instance?

**Comment by kabestrus** [comment]
The instance is ICC, the level is 80, and no, i didnt use any spell
I entered in gm mode, but my friends entered without gm mode and they have raid

**Comment by ariel-** [comment]
>  Both tables are empty

He enumerated 3 tables, not 2, just checking:

```sql
SELECT * FROM `instance`;
SELECT * FROM `character_instance`;
SELECT * FROM `group_instance`;
```

**Comment by kabestrus** [comment]
OH!! sorry, I only readed 2 tables...
But the answer is the same, the 3 tables are empty
16:50:21	SELECT * FROM characters.instance	
0 row(s) returned	
16:51:26	SELECT * FROM characters.character_instance	
0 row(s) returned	
16:51:45	SELECT * FROM characters.group_instance	
0 row(s) returned

**Comment by ariel-** [comment]
Just for the sake of it.. can you also run a DESC query on those tables too?

```sql
DESC `instance`;
DESC `character_instance`;
DESC `group_instance`;
```

**Comment by kabestrus** [comment]
Hi @ariel- 
-------------------------------------------
desc characters.instance;

'id', 'int(10) unsigned', 'NO', 'PRI', '0', ''
'map', 'smallint(5) unsigned', 'NO', 'MUL', '0', ''
'resettime', 'bigint(20) unsigned', 'NO', 'MUL', '0', ''
'difficulty', 'tinyint(3) unsigned', 'NO', 'MUL', '0', ''
'completedEncounters', 'int(10) unsigned', 'NO', '', '0', ''
'data', 'tinytext', 'NO', '', NULL, ''
-------------------------------------------
desc characters.character_instance;

'guid', 'int(10) unsigned', 'NO', 'PRI', '0', ''
'instance', 'int(10) unsigned', 'NO', 'PRI', '0', ''
'permanent', 'tinyint(3) unsigned', 'NO', '', '0', ''
'extendState', 'tinyint(2) unsigned', 'NO', '', '1', ''
-------------------------------------------
desc characters.group_instance;

'guid', 'int(10) unsigned', 'NO', 'PRI', '0', ''
'instance', 'int(10) unsigned', 'NO', 'PRI', '0', ''
'permanent', 'tinyint(3) unsigned', 'NO', '', '0', ''
-------------------------------------------

Ty

**Comment by Aokromes** [comment]
9d37c2b

**Comment by codeman8214** [comment]
Good glad to see this matter is fixed

**Comment by ariel-** [comment]
Only happened with -DCORE_DEBUG=1 which is disabled by default and recommended not to enable it; unless explicitly asked for by a developer

**Comment by kabestrus** [comment]
Okey,  but one question,  is not  COREDEBUG = 1  necessary in order to get debug crash report?

**Comment by Shauren** [comment]
No. On windows you build in Debug/RelWithDebInfo, on linux you use -DCMAKE_BUILD_TYPE=Debug

**Comment by kabestrus** [comment]
Ty for the support!!!!!

**Comment by Gooyeth** [comment]
The problem still occurs when the player login in instance.

Branch: 3.3.5
Rev: fa3eb75
SO: Debian 9

```
#0  Trinity::Assert (file=0x31078c0 "/home/trinity/server/sources/emu/src/server/game/Maps/MapManager.cpp", line=342, function=0x3107a01 "GenerateInstanceId", message=0x3107a14 "newInstanceId < _freeInstanceIds.size()") at /home/trinity/server/sources/emu/src/common/Debugging/Errors.cpp:43
No locals.
#1  0x000000000276ffcc in MapManager::GenerateInstanceId (this=0x3cb3ed0 <MapManager::instance()::instance>) at /home/trinity/server/sources/emu/src/server/game/Maps/MapManager.cpp:342
        newInstanceId = 2
        nextFreedId = 140737488328728
#2  0x0000000002c1cd30 in MapInstanced::CreateInstanceForPlayer (this=0x7fff15f35180, mapId=631, player=0x7fff4935df00, loginInstanceId=0) at /home/trinity/server/sources/emu/src/server/game/Maps/MapInstanced.cpp:188
        diff = Difficulty::REGULAR_DIFFICULTY
        pBind = 0x0
        pSave = 0x0
        map = 0x0
        newInstanceId = 0
#3  0x000000000276e66d in MapManager::CreateMap (this=0x3cb3ed0 <MapManager::instance()::instance>, id=631, player=0x7fff4935df00, loginInstanceId=0) at /home/trinity/server/sources/emu/src/server/game/Maps/MapManager.cpp:110
        m = 0x7fff15f35180
#4  0x0000000002364e88 in Player::LoadFromDB (this=0x7fff4935df00, guid=..., holder=0x7ffef50e4840) at /home/trinity/server/sources/emu/src/server/game/Entities/Player/Player.cpp:17349
        result = std::shared_ptr (count 2, weak 0) 0x7ffedf49a2f0
        fields = 0x7fff49a8b800
        dbAccountId = 161095
        gender = 0 '\000'
        info = 0x7fff551be720
        money = 141110
        transLowGUID = 0
        mapId = 631
        instanceId = 0
        dungeonDiff = 1
        raidDiff = 3
        taxi_nodes = <incomplete type>
        mapEntry = 0x7fffeb68c0b4
        map = 0x0
        player_at_bg = false
        areaTrigger = 0x9
        check = false
        now = 140733193388033
        logoutTime = 4096
        time_diff = 0
        newDrunkValue = 0 '\000'
        extraflags = 0
        curTitle = 0
        savedHealth = 32767
#5  0x0000000002bd6028 in WorldSession::HandlePlayerLogin (this=0x7ffef8174200, holder=0x7ffef50e4840) at /home/trinity/server/sources/emu/src/server/game/Handlers/CharacterHandler.cpp:721
        playerGuid = {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 592816}
        pCurrChar = 0x7fff4935df00
        chH = {_vptr$ChatHandler = 0x30c7d08 <vtable for ChatHandler+16>, m_session = 0x7ffef8174200, sentErrorMessage = false}
        data = {<ByteBuffer> = {_vptr$ByteBuffer = 0x7ffef8174220, static DEFAULT_SIZE = 4096, _rpos = 140733560043744, _wpos = 140733560043728, _storage = std::vector of length 4427645968, capacity -140733018034616 = {0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 66 'B', 23 '\027', 248 '\370', 254 '\376', 127 '\177', 0 '\000', 0 '\000', 1 '\001', 0 '\000', 0 '\000', 0 '\000', 255 '\377', 127 '\177', 0 '\000', 0 '\000', 32 ' ', 72 'H', 222 '\336', 21 '\025', 255 '\377', 127 '\177', 0 '\000', 0 '\000', 2 '\002', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 192 '\300', 197 '\305', 70 'F', 137 '\211', 255 '\377', 127 '\177', 0 '\000', 0 '\000', 1 '\001', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 128 '\200', 63 '?', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 2 '\002', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 88 'X', 229 '\345', 253 '\375', 241 '\361', 255 '\377', 127 '\177', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 160 '\240', 235 '\353', 127 '\177', 21 '\025', 255 '\377', 127 '\177', 0 '\000', 0 '\000', 112 'p', 235 '\353', 127 '\177', 21 '\025', 255 '\377', 127 '\177', 0 '\000', 0 '\000', 224 '\340', 237 '\355', 127 '\177', 21 '\025', 255 '\377', 127 '\177', 0 '\000', 0 '\000', 4 '\004', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 176 '\260', 11 '\v', 9 '\t', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 223 '\337', 53 '5', 73 'I', 255 '\377', 127 '\177', 0 '\000', 0 '\000', 144 '\220', 61 '=', 220 '\334', 247 '\367', 254 '\376', 127 '\177', 0 '\000', 0 '\000', 128 '\200', 61 '=', 220 '\334', 247 '\367', 254 '\376', 127 '\177', 0 '\000', 0 '\000', 240 '\360', 66 'B', 23 '\027', 248 '\370', 254 '\376', 127 '\177', 0 '\000', 0 '\000'...}}, m_opcode = 20544}
        stmt = 0x1
        firstLogin = false
        IP_str = <incomplete type>
#6  0x00000000028988a1 in WorldSession::ProcessQueryCallbacks (this=0x7ffef8174200) at /home/trinity/server/sources/emu/src/server/game/Server/WorldSession.cpp:1117
No locals.
#7  0x0000000002897298 in WorldSession::Update (this=0x7ffef8174200, diff=50, updater=...) at /home/trinity/server/sources/emu/src/server/game/Server/WorldSession.cpp:403
        packet = 0x0
        deletePacket = true
        requeuePackets = std::vector of length 0, capacity 0
        processedPackets = 0
        currentTime = 1516477976
#8  0x0000000002b8d05e in World::UpdateSessions (this=0x3cb93d8 <World::instance()::instance>, diff=50) at /home/trinity/server/sources/emu/src/server/game/World/World.cpp:2997
        pSession = 0x7ffef8174200
        updater = {<PacketFilter> = {_vptr$PacketFilter = 0x3116428 <vtable for WorldSessionFilter+16>, m_pSession = 0x7ffef8174200}, <No data fields>}
        itr = {<std::__detail::_Node_iterator_base<std::pair<unsigned int const, WorldSession*>, false>> = {_M_cur = 0x7fff14d5c380}, <No data fields>}
        next = {<std::__detail::_Node_iterator_base<std::pair<unsigned int const, WorldSession*>, false>> = {_M_cur = 0x7fffa5c63260}, <No data fields>}
        sess = 0x0
#9  0x0000000002b8ac24 in World::Update (this=0x3cb93d8 <World::instance()::instance>, diff=50) at /home/trinity/server/sources/emu/src/server/game/World/World.cpp:2337
        currentGameTime = 1516477976
#10 0x00000000017c50b3 in WorldUpdateLoop () at /home/trinity/server/sources/emu/src/server/worldserver/Main.cpp:429
        diff = 50
        executionTimeDiff = 41
        realCurrTime = 206201
        realPrevTime = 206151
#11 0x00000000017c18f1 in main (argc=2, argv=0x7fffffffe2e8) at /home/trinity/server/sources/emu/src/server/worldserver/Main.cpp:334
        configFile = {static preferred_separator = 47 '/', m_pathname = <incomplete type>}
        configService = <incomplete type>
        vm = <incomplete type>
        configError = <incomplete type>
        ioContext = std::shared_ptr (count 4, weak 0) 0x7ffff1f569d0
        opensslHandle = std::shared_ptr (count 1, weak 0) 0x0
        seed = {_bn = 0x7ffff1f84c60}
        pidFile = <incomplete type>
        signals = {<boost::asio::basic_io_object<boost::asio::signal_set_service, false>> = {service = @0x7ffff1fb9500, implementation = {queue_ = {<boost::asio::detail::noncopyable> = {<No data fields>}, front_ = 0x7ffff1f6ce40, back_ = 0x7ffff1f6ce40}, signals_ = 0x7ffff1f6ee00}}, <No data fields>}
        numThreads = 2
        threadPool = std::shared_ptr (count 1, weak 0) 0x7ffff1fb8be0
        dbHandle = std::shared_ptr (count 1, weak 0) 0x0
        sMetricHandle = std::shared_ptr (count 1, weak 0) 0x0
        sScriptMgrHandle = std::shared_ptr (count 1, weak 0) 0x0
        mapManagementHandle = std::shared_ptr (count 1, weak 0) 0x0
        raAcceptor = std::unique_ptr<AsyncAcceptor> containing 0x0
        soapThread = std::shared_ptr (count 1, weak 0) 0x7fff594251d8
        worldPort = 8085
        worldListener = <incomplete type>
        networkThreads = 3
        sWorldSocketMgrHandle = std::shared_ptr (count 1, weak 0) 0x0
        cliThread = std::shared_ptr (count 1, weak 0) 0x7fff59425210
        freezeDetector = std::shared_ptr (count 1, weak 1) 0x7fff11479130
```

**Comment by Jildor** [comment]
You should compile without coredebug

**Comment by Aokromes** [comment]
WITH_COREDEBUG is DEVELOPERS only flag, don't enable it.
