### ISSUE TITLE
Crash Npc High Overlord Saurfang

### ISSUE THREAD

**Issue by tje3d** [TrinityCore/TrinityCore#21644]
**Branch(es):** 3.3.5

**TC rev. hash/commit:** 29c1119

**TDB version:** TDB 335.64

**Operating system:** Debian 9

**Log:** https://gist.github.com/tje3d/be1645f85d6792ca8832cef6f1dd838a

**Comment by ariel-** [comment]
```cpp
            std::list<Creature*> _guardList;
```

Saving Creature* container instead of guids is a big no-no

**Comment by tkrokli** [comment]
... does that mean that the crash is caused by altered source code?

**Comment by tje3d** [comment]
@tkrokli its not

**Comment by tkrokli** [comment]
OK, very well. I just tried to interpret ariel-'s comment (and failed).

**Comment by eocrs** [comment]
Saurfang is crashing on latest revision: boss_deathbringer_saurfang.cpp line 692

**Comment by tkrokli** [comment]
@eocrs : so, this line?
https://github.com/TrinityCore/TrinityCore/blob/1c8d9af0846036fddef3aa8daf7506d0ebadddb9/src/server/scripts/Northrend/IcecrownCitadel/boss_deathbringer_saurfang.cpp#L692

**Comment by Strazhnik** [comment]
This crash after 28288698441524081d583af95f19cb1c9fb90387

**Comment by Gooyeth** [comment]
Maybe it's helpful:
```gdb
#0  0x0000000001b40c42 in npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::DoAction (this=0x7fff2894a3c0, action=-3781303) at /home/trinity/server/sources/emu/src/server/scripts/Northrend/IcecrownCitadel/boss_deathbringer_saurfang.cpp:692
        itr = 0x7fff1c4d9000
#1  0x0000000001b3f4c7 in boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::DamageTaken (this=0x7fff28946380, damage=@0x7ffecec0e594: 2438) at /home/trinity/server/sources/emu/src/server/scripts/Northrend/IcecrownCitadel/boss_deathbringer_saurfang.cpp:382
        creature = 0x7fff1c4df000
#2  0x000000000246b1da in Unit::DealDamage (attacker=0x7ffec0f3d580, victim=0x7ffec63ac000, damage=2438, cleanDamage=0x7ffecec0e9d0, damagetype=DamageEffectType::DOT, damageSchoolMask=SpellSchoolMask::SPELL_SCHOOL_MASK_FROST, spellProto=0x7fffdcf98d00, durabilityLoss=true) at /home/trinity/server/sources/emu/src/server/game/Entities/Unit/Unit.cpp:656
        rage_damage = 2438
        health = 32766
        duel_hasEnded = 206
        duel_wasMounted = 192
#3  0x0000000002b460e9 in AuraEffect::HandlePeriodicDamageAurasTick (this=0x7ffeb94b2c20, target=0x7ffec63ac000, caster=0x7ffec0f3d580) at /home/trinity/server/sources/emu/src/server/game/Spells/Auras/SpellAuraEffects.cpp:5212
        cleanDamage = {absorbed_damage = 0, mitigated_damage = 0, attackType = WeaponAttackType::BASE_ATTACK, hitOutCome = MeleeHitOutcome::MELEE_HIT_NORMAL}
        damage = 2438
        crit = false
        dmg = 2438
        damageInfo = {m_attacker = 0x7ffec0f3d580, m_victim = 0x7ffec63ac000, m_damage = 2438, m_spellInfo = 0x7fffdcf98d00, m_schoolMask = SpellSchoolMask::SPELL_SCHOOL_MASK_FROST, m_damageType = DamageEffectType::DOT, m_attackType = WeaponAttackType::BASE_ATTACK, m_absorb = 0, m_resist = 0, m_block = 0, m_hitMask = 0}
        absorb = 0
        resist = 0
        procAttacker = 262144
        procVictim = 1572864
        hitMask = 1
        overkill = 0
        pInfo = {auraEff = 0x7ffeb94b2c20, damage = 2438, overDamage = 0, absorb = 0, resist = 0, multiplier = 0, critical = false}
#4  0x0000000002b43e02 in AuraEffect::PeriodicTick (this=0x7ffeb94b2c20, aurApp=0x7fffbac76180, caster=0x7ffec0f3d580) at /home/trinity/server/sources/emu/src/server/game/Spells/Auras/SpellAuraEffects.cpp:883
        prevented = false
        target = 0x7ffec63ac000
#5  0x0000000002b43bdf in AuraEffect::Update (this=0x7ffeb94b2c20, diff=127, caster=0x7ffec0f3d580) at /home/trinity/server/sources/emu/src/server/game/Spells/Auras/SpellAuraEffects.cpp:835
        aurApp = 0x7fffbac76180
        __range = std::vector of length 1, capacity 1 = {0x7fffbac76180}
        __begin = 0x7fffbac76180
        __end = 0x3000000000
        effectApplications = std::vector of length 1, capacity 1 = {0x7fffbac76180}
        totalTicks = 7
#6  0x0000000002b58c8c in Aura::UpdateOwner (this=0x7ffec4780500, diff=127, owner=0x7ffec63ac000) at /home/trinity/server/sources/emu/src/server/game/Spells/Auras/SpellAuras.cpp:810
        i = 0 '\000'
        caster = 0x7ffec0f3d580
        modSpell = 0x0
        modOwner = 0x7ffec0f3d580
#7  0x0000000002469480 in Unit::_UpdateSpells (this=0x7ffec63ac000, time=127) at /home/trinity/server/sources/emu/src/server/game/Entities/Unit/Unit.cpp:2876
        i_aura = 0x7ffec4780500
#8  0x00000000024690f0 in Unit::Update (this=0x7ffec63ac000, p_time=127) at /home/trinity/server/sources/emu/src/server/game/Entities/Unit/Unit.cpp:427
No locals.
```

**Comment by irgc** [comment]
confirm

**Comment by Strazhnik** [comment]
Now crash after  kill Festergut

**Comment by Killyana** [comment]
@Strazhnik: New issue with the new crash log plz.

**Comment by Strazhnik** [comment]
New log:
https://gist.github.com/Strazhnik/97d6fe9ba53e54543bf4af0c5904b4b9

**Comment by Killyana** [comment]
It's related to a respawn issue:
<Creature::LoadFromDB(unsigned int, Map*, bool, bool)::__FUNCTION__> "LoadFromDB", message=message@entry=0x1dfbc68 "m_respawnCompatibilityMode || sPoolMgr->IsPartOfAPool<Creature>(spawnId)", format=format@entry=0x1dfbcb8 "Creature (SpawnID %u) trying to load despite a respawn timer in progress.")

**Comment by ariel-** [comment]
#21641?
