### ISSUE TITLE
[Crash] CheckRespawn ASSERTION FAILED

### ISSUE THREAD

**Issue by HAANAAE** [TrinityCore/TrinityCore#22890]
Description:
data
Invalid respawn info with type 0, spawnID 215540 in respawn queue.

Crash log

https://gist.github.com/HAANAAE/44088b3e7bb3890704ef71560395b081

Branch(es): 3.3.5
TC rev. hash/commit: https://github.com/TrinityCore/TrinityCore/commit/afdbc5ffe38e9b845f6ef123849139e846a540ae
Operating system: debian

**Comment by illfated** [comment]
Extended excerpt from the crash log to see the mentioned description in context:
```
Thread 7 "worldserver" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff4ddff700 (LWP 18015)]
0x000000000172abb5 in Trinity::Assert (file=<optimized out>, line=<optimized out>, function=<optimized out>, message=<optimized out>, format=0x1a18a30 "Invalid respawn info with type %u, spawnID %u in respawn queue.") at /home/TrinityCore/src/common/Debugging/Errors.cpp:91
91	    Crash(formattedMessage.c_str());

--- DEBUG: BACKTRACE FULL

/home/TrinityCore/src/server/game/Maps/Map.cpp:2927 in CheckRespawn ASSERTION FAILED:
  data
Invalid respawn info with type 0, spawnID 215540 in respawn queue.

#0  0x000000000172abb5 in Trinity::Assert (file=<optimized out>, line=<optimized out>, function=<optimized out>, message=<optimized out>, format=0x1a18a30 "Invalid respawn info with type %u, spawnID %u in respawn queue.") at /home/TrinityCore/src/common/Debugging/Errors.cpp:91
        args = {{gp_offset = 48, fp_offset = 48, overflow_arg_area = 0x7fff4ddfd548, reg_save_area = 0x7fff4ddfd460}}
        formattedMessage = <optimized out>
#1  0x0000000001396bb9 in Map::CheckRespawn (this=0x7fffb50a0ac0, info=0x7fff42b00a30) at /home/TrinityCore/src/server/game/Maps/Map.cpp:2927
        data = 0x0
        poolId = <optimized out>
        thisGUID = <optimized out>
#2  0x000000000138f571 in Map::ProcessRespawns (this=0x7fffb50a0ac0) at /home/TrinityCore/src/server/game/Maps/Map.cpp:3185
        next = 0x7fff42b00a30
        now = 1545824509
#3  0x000000000138ee2f in Map::Update (this=0x7fffb50a0ac0, t_diff=101) at /home/TrinityCore/src/server/game/Maps/Map.cpp:764
        updater = <optimized out>
        world_object_update = <optimized out>
        grid_object_update = <optimized out>
#4  0x000000000139e02d in InstanceMap::Update (this=0x7fffb50a0ac0, t_diff=101) at /home/TrinityCore/src/server/game/Maps/Map.cpp:3851
No locals.
#5  0x00000000013b4ce3 in MapUpdateRequest::call (this=0x7fffb9725aa0) at /home/TrinityCore/src/server/game/Maps/MapUpdater.cpp:42
No locals.
#6  0x00000000013b4739 in MapUpdater::WorkerThread (this=0x20d5800 <MapManager::instance()::instance+160>) at /home/TrinityCore/src/server/game/Maps/MapUpdater.cpp:113
        request = 0x7fff49dc9500
```

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/21519
