### ISSUE TITLE
Crash using mind control on Gormok the Impaler

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#24562]
**Description:**
Server will crash if:
1. Equip item https://www.wowhead.com/item=48945
2. Enter ToC 10/25
3. Spam the item spell on Gormok the Impaler

It will trigger https://github.com/TrinityCore/TrinityCore/blob/57a5969c2672b36160fea1b7c38c424de562a57b/src/server/game/Entities/Unit/Unit.cpp#L11806

**Branch(es):** 3.3.5
**TC rev. hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/9b5375f858b7a9bac409cc0b17c56391f2787f5b

**Comment by Riztazz** [comment]
Mind control cap has a chance to fail:
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Spells/spell_item.cpp#L4034
and this forces to Gormok to cast mindcontrol back on player, but on gormok encounter player is vehicle and it asserts. Player is vehicle because of gormok adds
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/instance_trial_of_the_crusader.cpp#L139
(Im pretty sure there is an aura for that)

**Comment by jackpoz** [comment]
why even assert when a return false; would work just fine...

**Comment by jackpoz** [comment]
callstack:
```
    #0 0x401dbd5 in Trinity::Assert(char const*, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*) /home/trinity/trinity/sources/src/common/Debugging/Errors.cpp:76:5
    #1 0x289399b in Unit::SetCharmedBy(Unit*, CharmType, AuraApplication const*) /home/trinity/trinity/sources/src/server/game/Entities/Unit/Unit.cpp:11376:5
    #2 0x3971ec0 in AuraEffect::HandleEffect(AuraApplication*, unsigned char, bool) /home/trinity/trinity/sources/src/server/game/Spells/Auras/SpellAuraEffects.cpp:732:9
    #3 0x39c34d5 in AuraApplication::_HandleEffect(unsigned char, bool) /home/trinity/trinity/sources/src/server/game/Spells/Auras/SpellAuras.cpp:176:17
    #4 0x2834016 in Unit::_ApplyAura(AuraApplication*, unsigned char) /home/trinity/trinity/sources/src/server/game/Entities/Unit/Unit.cpp:3370:21
    #5 0x37160b4 in Spell::TargetInfo::DoDamageAndTriggers(Spell*) /home/trinity/trinity/sources/src/server/game/Spells/Spell.cpp:2578:38
    #6 0x37569c8 in void Spell::DoProcessTargetContainer<std::vector<Spell::TargetInfo, std::allocator<Spell::TargetInfo> > >(std::vector<Spell::TargetInfo, std::allocator<Spell::TargetInfo> >&) /home/trinity/trinity/sources/src/server/game/Spells/Spell.cpp:3476:16
    #7 0x373348b in Spell::handle_immediate() /home/trinity/trinity/sources/src/server/game/Spells/Spell.cpp:3518:9
    #8 0x372b858 in Spell::_cast(bool) /home/trinity/trinity/sources/src/server/game/Spells/Spell.cpp:3409:9
    #9 0x371b812 in Spell::cast(bool) /home/trinity/trinity/sources/src/server/game/Spells/Spell.cpp:3190:5
    #10 0x371b812 in Spell::prepare(SpellCastTargets const&, AuraEffect const*) /home/trinity/trinity/sources/src/server/game/Spells/Spell.cpp:3087:9
    #11 0x23d21f5 in WorldObject::CastSpell(SpellCastTargets const&, unsigned int, CastSpellExtraArgs const&) /home/trinity/trinity/sources/src/server/game/Entities/Object/Object.cpp:2800:19
    #12 0x23d29d1 in WorldObject::CastSpell(WorldObject*, unsigned int, CastSpellExtraArgs const&) /home/trinity/trinity/sources/src/server/game/Entities/Object/Object.cpp:2818:12
    #13 0x18f24c8 in spell_item_mind_control_cap::HandleDummy(SpellEffIndex) /home/trinity/trinity/sources/src/server/scripts/Spells/spell_item.cpp:4034:25
    #14 0x3743b14 in Spell::CallScriptEffectHandlers(SpellEffIndex, SpellEffectHandleMode) /home/trinity/trinity/sources/src/server/game/Spells/Spell.cpp:7843:27
    #15 0x3718f16 in Spell::HandleEffects(Unit*, Item*, GameObject*, unsigned int, SpellEffectHandleMode) /home/trinity/trinity/sources/src/server/game/Spells/Spell.cpp:5033:27
    #16 0x37140d0 in Spell::DoSpellEffectHit(Unit*, unsigned char, Spell::TargetInfo&) /home/trinity/trinity/sources/src/server/game/Spells/Spell.cpp:2828:5
    #17 0x37135df in Spell::TargetInfo::DoTargetSpellHit(Spell*, unsigned char) /home/trinity/trinity/sources/src/server/game/Spells/Spell.cpp:2335:16
    #18 0x3756a1b in void Spell::DoProcessTargetContainer<std::vector<Spell::TargetInfo, std::allocator<Spell::TargetInfo> > >(std::vector<Spell::TargetInfo, std::allocator<Spell::TargetInfo> >&) /home/trinity/trinity/sources/src/server/game/Spells/Spell.cpp:3473:24
    #19 0x373348b in Spell::handle_immediate() /home/trinity/trinity/sources/src/server/game/Spells/Spell.cpp:3518:9
    #20 0x372b858 in Spell::_cast(bool) /home/trinity/trinity/sources/src/server/game/Spells/Spell.cpp:3409:9
    #21 0x3739644 in Spell::cast(bool) /home/trinity/trinity/sources/src/server/game/Spells/Spell.cpp:3190:5
    #22 0x3739644 in Spell::update(unsigned int) /home/trinity/trinity/sources/src/server/game/Spells/Spell.cpp:3744:17
    #23 0x3750ce9 in SpellEvent::Execute(unsigned long, unsigned int) /home/trinity/trinity/sources/src/server/game/Spells/Spell.cpp:7368:18
    #24 0x3fe4816 in EventProcessor::Update(unsigned int) /home/trinity/trinity/sources/src/common/Utilities/EventProcessor.cpp:55:24
    #25 0x27f667b in Unit::Update(unsigned int) /home/trinity/trinity/sources/src/server/game/Entities/Unit/Unit.cpp:427:14
    #26 0x24818b8 in Player::Update(unsigned int) /home/trinity/trinity/sources/src/server/game/Entities/Player/Player.cpp:1041:11
    #27 0x30ebfc7 in Map::Update(unsigned int) /home/trinity/trinity/sources/src/server/game/Maps/Map.cpp:799:17
    #28 0x3123a34 in InstanceMap::Update(unsigned int) /home/trinity/trinity/sources/src/server/game/Maps/Map.cpp:3860:10
    #29 0x31c5d35 in MapUpdateRequest::call() /home/trinity/trinity/sources/src/server/game/Maps/MapUpdater.cpp:41:19
    #30 0x31c4992 in MapUpdater::WorkerThread() /home/trinity/trinity/sources/src/server/game/Maps/MapUpdater.cpp:112:18
    #31 0x7f00e773dcb3  (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xd6cb3)
    #32 0x7f00e786f608 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x9608)
    #33 0x7f00e741a102 in clone (/lib/x86_64-linux-gnu/libc.so.6+0x122102)
```

**Comment by Shauren** [comment]
You can't just return, that aura cannot be left alone without applying its effect (the mind control)

**Comment by Rushor** [comment]
https://de.classic.wowhead.com/item=10726/gnomen-gedankenkontrollkappe#comments:id=1146

Your target becomes like a hunter pet. You have the attack/follow/stay and agressive/defensive/passive buttons.

If you control an NPC, you also get buttons for their abilities (or the first 4, though most monsters have only one or two... if it has 5 abilities it's probably a boss and immune).

i guess spell should always fail is target is a boss. will sreach more on this
