### ISSUE TITLE
Core/Packets: SMSG_SPELL_GO and EndOfStreamException

### ISSUE THREAD

**Issue by Faq** [TrinityCore/TrinityCore#25354]
**Description:**

[SpellHandler.cs:line 728](https://github.com/TrinityCore/WowPacketParser/blob/6fc34f1deb4d92b385886495ca98c21cc772e71c/WowPacketParser/Parsing/Parsers/SpellHandler.cs#L728) converted here [Core/Spell: fix spell visual for other players](https://github.com/TrinityCore/TrinityCore/commit/0c2a6dee0781be56bdee81e4d155431d7e7634f1#diff-60d9a03e2019001eb9763fa13bf775f6) 

While checking packetlog, got this:
```
ServerToClient: SMSG_SPELL_GO (0x0132) Length: 17 ConnIdx: 0 EP: 100.10.1.114:6166 Time: 08/29/2020 00:03:41.990 Number: 198
Caster GUID: Full: 0x00000004 Type: Player Low: 4 Name: Lock
Caster Unit GUID: Full: 0x00000004 Type: Player Low: 4 Name: Lock
Cast Count: 0
Spell ID: 688 (688)
Cast Flags: 256 (Unknown7)
Time: 0
System.IO.EndOfStreamException
Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.ReadByte()
   at WowPacketParser.Misc.Packet.ReadByte(String name, Object[] indexes) in C:\projects\wowpacketparser-191\WowPacketParser\Misc\PacketReads.cs:line 313
   at WowPacketParser.Parsing.Parsers.SpellHandler.HandleSpellStart(Packet packet) in C:\projects\wowpacketparser-191\WowPacketParser\Parsing\Parsers\SpellHandler.cs:line 728
   at WowPacketParser.Parsing.Handler.Parse(Packet packet, Boolean isMultiple) in C:\projects\wowpacketparser-191\WowPacketParser\Parsing\Handler.cs:line 149
```

**Expected behavior:**

No exception

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

5d2780c43c36b0ae1cc4ac2694bf6ec464d079c7

**Comment by Shauren** [comment]
Fun fact: not caused by packet porting at all. Been always broken
