### ISSUE TITLE
Onyxia and SMSG_MOVE_SPLINE with exceptions

### ISSUE THREAD

**Issue by Faq** [TrinityCore/TrinityCore#25461]
**Description:**
While checking onyxia, she flying and between going to other movepoint animation is frozen in air. 

And got this:
```
ServerToClient: SMSG_MOVE_SPLINE_UNSET_FLYING (0x0423) Length: 6 ConnIdx: 0 EP: 100.10.1.114:5410 Time: 09/15/2020 21:21:59.081 Number: 1495
Guid: Full: 0xF1300027C8000008 Type: Creature Entry: 10184 Low: 8
System.IO.EndOfStreamException
Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at System.IO.BinaryReader.ReadInt32()
   at WowPacketParser.Misc.Packet.ReadValue(TypeCode code) in C:\projects\wowpacketparser-191\WowPacketParser\Misc\PacketReads.cs:line 548
   at WowPacketParser.Misc.Packet.ReadValue[T]() in C:\projects\wowpacketparser-191\WowPacketParser\Misc\PacketReads.cs:line 527
   at WowPacketParser.Misc.Packet.ReadEnum[TEnum,T]() in C:\projects\wowpacketparser-191\WowPacketParser\Misc\PacketReads.cs:line 565
   at WowPacketParser.Misc.Packet.ReadEnum[TEnum,T](String name, Object[] indexes) in C:\projects\wowpacketparser-191\WowPacketParser\Misc\PacketReads.cs:line 279
   at WowPacketParser.Misc.Packet.ReadInt32E[TEnum](String name, Object[] idx) in C:\projects\wowpacketparser-191\WowPacketParser\Misc\PacketReads.cs:line 288
   at WowPacketParser.Parsing.Parsers.MovementHandler.ReadMovementInfoGen(Packet packet, WowGuid guid, Object index) in C:\projects\wowpacketparser-191\WowPacketParser\Parsing\Parsers\MovementHandler.cs:line 34
   at WowPacketParser.Parsing.Parsers.MovementHandler.ReadMovementInfo(Packet packet, WowGuid guid, Object index) in C:\projects\wowpacketparser-191\WowPacketParser\Parsing\Parsers\MovementHandler.cs:line 29
   at WowPacketParser.Parsing.Parsers.MovementHandler.HandleSplineFlyMovementMessages(Packet packet) in C:\projects\wowpacketparser-191\WowPacketParser\Parsing\Parsers\MovementHandler.cs:line 1772
   at WowPacketParser.Parsing.Handler.Parse(Packet packet, Boolean isMultiple) in C:\projects\wowpacketparser-191\WowPacketParser\Parsing\Handler.cs:line 149

ServerToClient: SMSG_MOVE_SPLINE_SET_FLYING (0x0422) Length: 6 ConnIdx: 0 EP: 100.10.1.114:5410 Time: 09/15/2020 21:22:44.362 Number: 1499
Guid: Full: 0xF1300027C8000008 Type: Creature Entry: 10184 Low: 8
System.IO.EndOfStreamException
Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at System.IO.BinaryReader.ReadInt32()
   at WowPacketParser.Misc.Packet.ReadValue(TypeCode code) in C:\projects\wowpacketparser-191\WowPacketParser\Misc\PacketReads.cs:line 548
   at WowPacketParser.Misc.Packet.ReadValue[T]() in C:\projects\wowpacketparser-191\WowPacketParser\Misc\PacketReads.cs:line 527
   at WowPacketParser.Misc.Packet.ReadEnum[TEnum,T]() in C:\projects\wowpacketparser-191\WowPacketParser\Misc\PacketReads.cs:line 565
   at WowPacketParser.Misc.Packet.ReadEnum[TEnum,T](String name, Object[] indexes) in C:\projects\wowpacketparser-191\WowPacketParser\Misc\PacketReads.cs:line 279
   at WowPacketParser.Misc.Packet.ReadInt32E[TEnum](String name, Object[] idx) in C:\projects\wowpacketparser-191\WowPacketParser\Misc\PacketReads.cs:line 288
   at WowPacketParser.Parsing.Parsers.MovementHandler.ReadMovementInfoGen(Packet packet, WowGuid guid, Object index) in C:\projects\wowpacketparser-191\WowPacketParser\Parsing\Parsers\MovementHandler.cs:line 34
   at WowPacketParser.Parsing.Parsers.MovementHandler.ReadMovementInfo(Packet packet, WowGuid guid, Object index) in C:\projects\wowpacketparser-191\WowPacketParser\Parsing\Parsers\MovementHandler.cs:line 29
   at WowPacketParser.Parsing.Parsers.MovementHandler.HandleSplineFlyMovementMessages(Packet packet) in C:\projects\wowpacketparser-191\WowPacketParser\Parsing\Parsers\MovementHandler.cs:line 1772
   at WowPacketParser.Parsing.Handler.Parse(Packet packet, Boolean isMultiple) in C:\projects\wowpacketparser-191\WowPacketParser\Parsing\Handler.cs:line 149

ServerToClient: SMSG_MOVE_SPLINE_DISABLE_GRAVITY (0x04D3) Length: 6 ConnIdx: 0 EP: 100.10.1.114:5410 Time: 09/15/2020 21:22:48.879 Number: 1501
GUID: Full: 0xF1300027C8000008 Type: Creature Entry: 10184 Low: 8

```

**Expected behaviour:**

No exceptions

**Steps to reproduce the problem:**
1. .go c id 10184
2. Damage onyxia around 50%, she will walk to the entry of room and fly up (phase 2), there will occur first animation freeze

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 
0d152e932cdd986f62ae22bd9fc40569892a2453

**Comment by Shauren** [comment]
WPP is completely wrong here, it has wrong structure (not TC)

**Comment by Shauren** [comment]
Also, is this onyxia report or wpp report? wpp is now fixed and this is not wpp issue tracker
