### ISSUE TITLE
Crash in instance_blackrock_spireMapScript::~instance_blackrock_spireMapScript

### ISSUE THREAD

**Issue by gtestdev** [TrinityCore/TrinityCore#26589]
**Description:**

Crashlog: https://gist.github.com/gtestdev/85570e5533cc1c05446432803344a0a3
it happens from time to time, it's not a new crash.

**Steps to reproduce the problem:**

I don't know how to reproduce it.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

f418631de0c193772e24f379db5aafcc01f3fb6a

**Operating system:** 

Debian10

**Comment by Jinnaix** [comment]
I would bet that you modified BWL up to some degree since in stock Trinitycore you cant even do the first boss at all.
Without a full overview of your changes to BWL, no one is able to help you.

**Comment by gtestdev** [comment]
I don't have modified anything

**Comment by Ovahlord** [comment]
My guts tell me that this isnt true because the crash happens at a spot that does not exist in stock TC

**Comment by gtestdev** [comment]
I don't care what your guts can tell the truth, I have reported a crash and I have nothing modified, it is not a new crash, but I have no idea how to reproduce it, If you have nothing to contribute to help solve it, better not put anything please.

in crashlog appear <instance_blackrock_spire::instance_blackrock_spireMapScript::OnCreatureCreate(Creature*)>:
but I do not understand very well how it is possible that it can crash because of that when the mapinstance is destroyed

maybe need add InstanceScript::OnCreatureCreate(creature); inside void OnCreatureCreate(Creature* creature) override ?

**Comment by Shauren** [comment]
@Ovahlord you are wrong here. A destructor must always exist and compiler WILL generate one if you dont provide it yourself - in which case stack trace may point to any line that wont be valid if crash happens inside it

**Comment by jackpoz** [comment]
We could try running that instance in https://tcubuntu.northeurope.cloudapp.azure.com/ (even just entering and exploring it) as that runs with Address Sanitizer and can spot issues that can cause crashes

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/blob/2acdd163fea281f467f074d267e45660fc9bf99d/src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/instance_blackrock_spire.cpp#L429-L434

https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/instance_blackrock_spire.cpp#L534

Pretty sure this writes out of bounds if one manually spawns more of the mobs defined at https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/instance_blackrock_spire.cpp#L29  (or if for some reason there are more mobs ingame)

**Comment by Ovahlord** [comment]
aight, provided a pr with the possible solution. please try and report back. This might also fix the issue with the door not opening

**Comment by jackpoz** [comment]
Spawned a few `.npc add temp 9817`, ASan reported out of bounds write
<details>
  <summary>Address Sanitizer report</summary>

  ```
==171122==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x619006e6ee90 at pc 0x0000007f2812 bp 0x7f54c7200af0 sp 0x7f54c7200ae8
WRITE of size 8 at 0x619006e6ee90 thread T6
    #0 0x7f2811 in instance_blackrock_spire::instance_blackrock_spireMapScript::Dragonspireroomstore() /trinity/trinity/sources/src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/instance_blackrock_spire.cpp:434:68
    #1 0x7f07f7 in instance_blackrock_spire::instance_blackrock_spireMapScript::Update(unsigned int) /trinity/trinity/sources/src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/instance_blackrock_spire.cpp:402:25
    #2 0x32ef695 in MapUpdateRequest::call() /trinity/trinity/sources/src/server/game/Maps/MapUpdater.cpp:43:19
    #3 0x32ee322 in MapUpdater::WorkerThread() /trinity/trinity/sources/src/server/game/Maps/MapUpdater.cpp:118:18
    #4 0x7f54e913b693  (/lib/x86_64-linux-gnu/libstdc++.so.6+0xda693)
    #5 0x7f54e92a144f in start_thread nptl/pthread_create.c:473:8
    #6 0x7f54e8e11d52 in clone misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95

0x619006e6ee90 is located 0 bytes to the right of 1040-byte region [0x619006e6ea80,0x619006e6ee90)
allocated by thread T0 here:
    #0 0x61c38d in operator new(unsigned long) (/trinity/trinity/bin/worldserver+0x61c38d)
    #1 0x7edd73 in instance_blackrock_spire::GetInstanceScript(InstanceMap*) const /trinity/trinity/sources/src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/instance_blackrock_spire.cpp:542:16
    #2 0x346d5da in ScriptMgr::CreateInstanceData(InstanceMap*) /trinity/trinity/sources/src/server/game/Scripting/ScriptMgr.cpp:1525:23
    #3 0x322e242 in InstanceMap::CreateInstanceData(bool) /trinity/trinity/sources/src/server/game/Maps/Map.cpp:3980:30
    #4 0x3edd3e2 in MapInstanced::CreateInstance(unsigned int, InstanceSave*, Difficulty, TeamId) /trinity/trinity/sources/src/server/game/Maps/MapInstanced.cpp:235:10
    #5 0x306c3d6 in WorldSession::HandleMoveWorldportAck() /trinity/trinity/sources/src/server/game/Handlers/MovementHandler.cpp:75:28
    #6 0x306b998 in WorldSession::HandleMoveWorldportAckOpcode(WorldPacket&) /trinity/trinity/sources/src/server/game/Handlers/MovementHandler.cpp:44:5
    #7 0x3526c43 in WorldSession::Update(unsigned int, PacketFilter&) /trinity/trinity/sources/src/server/game/Server/WorldSession.cpp:346:35
    #8 0x3d04f44 in World::UpdateSessions(unsigned int) /trinity/trinity/sources/src/server/game/World/World.cpp:3110:24
    #9 0x3cfb651 in World::Update(unsigned int) /trinity/trinity/sources/src/server/game/World/World.cpp:2416:9
    #10 0x633802 in WorldUpdateLoop() /trinity/trinity/sources/src/server/worldserver/Main.cpp:441:17
    #11 0x624542 in main /trinity/trinity/sources/src/server/worldserver/Main.cpp:342:5
    #12 0x7f54e8d22564 in __libc_start_main csu/../csu/libc-start.c:332:16

Thread T6 created by T0 here:
    #0 0x5d562c in pthread_create (/trinity/trinity/bin/worldserver+0x5d562c)
    #1 0x7f54e913b969 in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) (/lib/x86_64-linux-gnu/libstdc++.so.6+0xda969)
    #2 0x3cc55ff in World::SetInitialWorldSettings() /trinity/trinity/sources/src/server/game/World/World.cpp:2147:14
    #3 0x6220ac in main /trinity/trinity/sources/src/server/worldserver/Main.cpp:253:13
    #4 0x7f54e8d22564 in __libc_start_main csu/../csu/libc-start.c:332:16

SUMMARY: AddressSanitizer: heap-buffer-overflow /trinity/trinity/sources/src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/instance_blackrock_spire.cpp:434:68 in instance_blackrock_spire::instance_blackrock_spireMapScript::Dragonspireroomstore()
Shadow bytes around the buggy address:
  0x0c3280dc5d80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3280dc5d90: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3280dc5da0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3280dc5db0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3280dc5dc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c3280dc5dd0: 00 00[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3280dc5de0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3280dc5df0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3280dc5e00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3280dc5e10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3280dc5e20: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
=================================================================
  ```

![image](https://user-images.githubusercontent.com/1153754/121778767-b5c53580-cb98-11eb-85a4-3d1709dca0ab.png)

</details>

**Comment by jackpoz** [comment]
@gtestdev thanks for the bug report, it allowed to fix a 8 years old memory corruption bug that over the years probably triggered random crashes with strange stracktraces.

**Comment by gtestdev** [comment]
thanks, i will try it
